commands/files/serialfile: Non-blocking open
Without the O_NONBLOCK flag:

  Open("/path/to/named-pipe")

will hang in a syscall (on Linux 4.1.0-rc8 anyway).  The Go
stack-trace looks like:

  syscall.Syscall(0x2, 0xc20969e870, 0x80000, 0x0, 0x0, 0xc2096ad040, 0xc2089a7a78)
          /usr/lib/go/src/syscall/asm_linux_amd64.s:21 +0x5 fp=0xc2089a79f8 sp=0xc2089a79f0
  syscall.open(0xc20969e840, 0x8, 0x80000, 0x0, 0x0, 0x0, 0x0)
          /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:16 +0xaa fp=0xc2089a7a58 sp=0xc2089a79f8
  syscall.Open(0xc20969e840, 0x8, 0x80000, 0x0, 0x12, 0x0, 0x0)
          /usr/lib/go/src/syscall/syscall_linux.go:23 +0x5a fp=0xc2089a7a98 sp=0xc2089a7a58
  os.OpenFile(0xc20969e840, 0x8, 0x0, 0x0, 0xc2089a7bd0, 0x0, 0x0)
          /usr/lib/go/src/os/file_unix.go:78 +0x6f fp=0xc2089a7af0 sp=0xc2089a7a98
  os.Open(0xc20969e840, 0x8, 0xc2089a7bd0, 0x0, 0x0)
          /usr/lib/go/src/os/file.go:239 +0x55 fp=0xc2089a7b30 sp=0xc2089a7af0
  github.com/ipfs/go-ipfs/commands/files.(*serialFile).NextFile(0xc20806dd80, 0x0, 0x0, 0x0, 0x0)
          /home/wking/src/go/src/github.com/ipfs/go-ipfs/commands/files/serialfile.go:90 +0x3e0 fp=0xc2089a7c60 sp=0xc2089a7b30
  ...

With this non-blocking open, the open (unsurprisingly ;) doesn't
block.  I haven't audited downstream usuage to make sure it handles a
non-blocking file, but with this change I get:

  $ ipfs add -r /path/to/dir
  Error: `/path/to/dir/named-pipe` is neither a directory nor a file

instead of the hung syscall when the named pipe has no data in it.

License: MIT
Signed-off-by: W. Trevor King <wking@tremily.us>