commands/cli/parse: Non-blocking open
Without the O_NONBLOCK flag:

  Open("/path/to/named-pipe")

will hang in a syscall (on Linux 4.1.0-rc8 anyway).  The Go
stack-trace looks like:

  syscall.Syscall(0x2, 0xc208080d51, 0x80000, 0x0, 0x0, 0x1, 0x41a31f)
          /usr/lib/go/src/syscall/asm_linux_amd64.s:21 +0x5 fp=0xc2080a75c8 sp=0xc2080a75c0
  syscall.open(0x7ffc89956140, 0x8, 0x80000, 0x100000000, 0x0, 0x0, 0x0)
          /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:16 +0xaa fp=0xc2080a7628 sp=0xc2080a75c8
  syscall.Open(0x7ffc89956140, 0x8, 0x80000, 0x0, 0x6, 0x0, 0x0)
          /usr/lib/go/src/syscall/syscall_linux.go:23 +0x5a fp=0xc2080a7668 sp=0xc2080a7628
  os.OpenFile(0x7ffc89956140, 0x8, 0x0, 0x0, 0x7f0f795e2408, 0x0, 0x0)
          /usr/lib/go/src/os/file_unix.go:78 +0x6f fp=0xc2080a76c0 sp=0xc2080a7668
  os.Open(0x7ffc89956140, 0x8, 0xc3b680, 0x0, 0x0)
          /usr/lib/go/src/os/file.go:239 +0x55 fp=0xc2080a7700 sp=0xc2080a76c0
  github.com/ipfs/go-ipfs/commands/cli.appendFile(0xc208080d70, 0x0, 0x1, 0xc20802a930, 0x1, 0x3, 0x11c3460, 0xc208080d01, 0x0, 0x0, ...)
          /home/wking/src/go/src/github.com/ipfs/go-ipfs/commands/cli/parse.go:342 +0xbb fp=0xc2080a7810 sp=0xc2080a7700
  ...

With this non-blocking open, the open (unsurprisingly ;) doesn't
block.  I haven't audited downstream usuage to make sure it handles a
non-blocking file, but with this change I get:

  $ ipfs add -r /path/to/namrd-pipe
  Error: `/path/to/named-pipe` is neither a directory nor a file

instead of the hung syscall when the named pipe has no data in it.

License: MIT
Signed-off-by: W. Trevor King <wking@tremily.us>